export { apiClient, setAuthStore, ApiError } from './client'
export { authApi } from './auth'
export { agentApi } from './agent'
export { knowledgeApi } from './knowledge'
export { workspaceApi } from './workspace'
export { extensionsApi } from './extensions'
export { dashboardApi } from './dashboard'
export { systemApi } from './system'
export { userApi } from './user'